#! /bin/sh

# File to track battery full status
status_file="/tmp/battery_status"

# Check battery capacity and charge status
battery_capacity=$(cat /sys/class/power_supply/BAT0/capacity)
battery_charge_status=$(cat /sys/class/power_supply/BAT0/status)

batstat=""
case $battery_charge_status in
    "Charging")
	batstat=" "
        ;;
    "Full")
	if [ "$(cat $status_file 2>/dev/null)" != "Full" ]; then
            notify-send " Battery fully charged" "You can disconnect the charger"
	fi
	;;
esac

# Update status file
echo "$battery_charge_status" > "$status_file"

bat=""
if [ "$battery_capacity" -ge 90 ]; then
    bat=""
elif [ "$battery_capacity" -ge 75 ]; then
    bat=""
elif [ "$battery_capacity" -ge 35 ]; then
    bat=""
elif [ "$battery_capacity" -ge 10 ]; then
    bat=""
else
    if [ "$battery_charge_status" = "Charging" ]; then
	  bat=""
    else
        notify-send --urgency=critical " Battery critical" "Charge your computer"
       	bat=" "
    fi
fi

printf "$batstat$bat $battery_capacity%%"

