#!/bin/sh

# Script for setting screen brightness and showing notification

get_brightness() {
    brightness=$(brightnessctl | grep Current | awk '{ print $4 }' | sed 's/[][()%]//g')
    echo $brightness
}

notify() {
    notify-send --icon=video-display -h int:value:"$(get_brightness)%" "Brightness" "$(get_brightness)%"
}

set_brightness() {
    brightnessctl set "$1"
}

if [ $1 = "up" ]; then
    set_brightness "5%+"
    notify
elif [ $1 = "down" ]; then
    set_brightness "5%-"
     notify
elif [ $1 = "setbrightness" ]; then
		if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
			br=$(echo "" | rofi -dmenu -l 0 -p "Set Brightness:")
		else
			br=$(echo "" | dmenu -l 0 -c -p "Set Brightness:")
		fi
    if [ $? -eq 0 ] && [ $br -gt -1 ] && [ $br -lt 101 ]; then
        set_brightness "$br%"
        notify
    fi
else
    notify
fi
