#!/bin/sh

# Select and stow dotfile folders using fzf

# Dotfiles directory
DOTFILES_DIR="$HOME/dots"

# Define color codes
RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
CYAN="\033[1;36m"
NC="\033[0m"

# Display message with borders
msg() {
    msg=" $1 "
    color_var="${2:-GREEN}"
    color=$(eval echo "\$$color_var")

    border=$(echo "$msg" | sed 's/./-/g')
    echo -e "$CYAN$border"
    echo -e "$color$msg"
    echo -e "$CYAN$border$NC"
}

# Check if DOTFILES_DIR exists
if [ ! -d "$DOTFILES_DIR" ]; then
    echo -e "${RED}Error: Dotfiles directory '$DOTFILES_DIR' does not exist.${NC}"
    echo -e "${GREEN}Cloning dotfiles to '$DOTFILES_DIR'.${NC}"
    git clone git@github.com:sagevik/dots.git "$DOTFILES_DIR"
    # clone zsh plugins
    if [ ! -d "$DOTFILES_DIR/zsh/.config/zsh/plugins" ]; then
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$DOTFILES_DIR/zsh/.config/zsh/plugins/zsh-syntax-highlighting"
        git clone https://github.com/zsh-users/zsh-autosuggestions.git "$DOTFILES_DIR/zsh/.config/zsh/plugins/zsh-autosuggestions"
    fi
fi

# List all folders in DOTFILES_DIR, excluding README.md
list_folders() {
    ls -d "$DOTFILES_DIR"/*/ | grep -v "README.md" | while read -r folder; do
        basename "$folder"
    done
}

# Main script
msg "Dotfiles Stow Manager"

# Pass folders to fzf for multi-selection
selected_folders=$(list_folders | fzf --multi --prompt="> " --header="Select folders to stow (up/dn/tab to (de)select)" --layout=reverse --border=rounded)

# Check if any folders were selected
if [ -z "$selected_folders" ]; then
    echo -e "${YELLOW}No folders selected. Exiting.${NC}"
    exit 0
fi

# Unstow and stow each selected folder
for folder in $selected_folders; do
    echo -e "${CYAN}Unstowing $folder...${NC}"
    if stow -D -d "$DOTFILES_DIR" -t "$HOME" "$folder"; then
        echo -e "Folder $folder -> ${GREEN}unstowed successfully${NC}"
    else
        echo -e "Folder $folder -> ${RED}failed to unstow${NC}"
    fi

    echo -e "${CYAN}Stowing $folder...${NC}"
    if stow -d "$DOTFILES_DIR" -t "$HOME" "$folder"; then
        echo -e "Folder $folder -> ${GREEN}stowed successfully${NC}"
    else
        echo -e "Folder $folder -> ${RED}failed to stow${NC}"
    fi
done

msg "Stowing complete" "GREEN"
