#!/bin/sh

layoutsdir="$HOME/.screenlayout"
set_with_arandr="arandr"
menu="dmenu -i -l 10 -p"

run_dmenu() {
    { ls "$layoutsdir"; echo "$set_with_arandr"; } | $menu "Choose monitor setup"
}

postrun() {
    wallpaper --reload
}

chosen="$(run_dmenu)"
if [ "$chosen" == "$set_with_arandr" ]; then
    arandr
else
    "$layoutsdir/$chosen"
fi

postrun

