#!/bin/sh

layoutsdir="$HOME/scripts/screenlayouts"
set_with_arandr="arandr"

run_dmenu() {
    { ls "$layoutsdir"; echo "$set_with_arandr"; } | dmenu -i -l 20 -p "Choose monitor setup"
}

postrun() {
    wallpaper --reload
}

chosen="$(run_dmenu)"
if [ "$chosen" == "$set_with_arandr" ]; then
    arandr
else
    "$layoutsdir/$chosen"
fi

postrun

