#!/bin/sh

font="Hack:size=16"

# Pass variables to dmenu
run_dmenu() {
	printf "Lock\nSuspend\nLogout\nReboot\nShutdown" | sort | dmenu -fn "$font" -i -c -l 5 -p "?"
}

chosen="$(run_dmenu)"
case $chosen in
    "Lock")
        slock
        ;;
    "Suspend")
        slock &
        sleep 1
        systemctl suspend
        ;;
    "Logout")
        pkill -KILL -u $USER
        ;;
    "Reboot")
        systemctl reboot
        ;;
    "Shutdown")
        systemctl poweroff
        ;;
    *)
        # 
        ;;
esac

