#! /usr/bin/sh

# Record video and/or audio screencapture

choice=$(printf "Video/Audio\nVideo\nAudio" | dmenu -i -p "Record:")
echo $choice

case $choice in
    "Video") ffmpeg -y -f x11grab -i :0.0 test.mkv ;;
    "Audio") ffmpeg -y -f alsa -i default test.mkv ;;
    "Video/Audio") ffmpeg -y -f x11grab -i :0.0 -f alsa -i default test.mkv ;;
    *) exit ;;
esac

# video
#ffmpeg -y -f x11grab -i :0.0 test.mkv

# audio
#ffmpeg -y -f alsa -i default test.mkv

#ffmpeg -y -f x11grab -i :0.0 -f alsa -i default test.mkv
