#!/bin/sh
TMPDIR="/tmp/tempstatusfiles"
TMPFILE="/tmp/tempstatus"

RECTEMPFILE="$TMPDIR/$(basename "$0")"
RECTEMPINFO=" "

VIDEODIR="$HOME/vid/screencasts"

[ -f "$TMPFILE" ] || echo "" > "$TMPFILE"
[ -d "$TMPDIR" ] || mkdir -p "$TMPDIR"

write_statusfile() {
    (
        flock 9
        content=""
        
        for file in "$TMPDIR"/*; do
            if [ -f "$file" ]; then
                content+=$(cat "$file")
                content+=$' '
            fi
        done
        
        echo "$content" > "$TMPFILE"
    ) 9>/tmp/tempstatus.lock
}

update_status() {
    write_statusfile
    pkill -RTMIN+5 slstatus
}

if pgrep -x "ffmpeg" > /dev/null; then
    KILL=$(printf "Yes\nNo" | dmenu -i -p "Stop recording?")
    case $KILL in
        "Yes")
            pkill -x "ffmpeg"
            notify-send "Recording" "Screen recording ended"
            rm "$RECTEMPFILE"
            update_status
            exit 0
            ;;
        "No")
            exit 0
            ;;
    esac
else
    TITLE=$(printf "" | dmenu -i -p "Enter recording title:")
    if [ -z "$TITLE" ]; then notify-send "Capture cancelled" && exit 0; fi

    TITLE="$(echo $TITLE | sed 's/ /_/g')"
    FILENAME="$TITLE-$(date '+%s')"
    mkdir -p "$VIDEODIR"
    ffmpeg -loglevel quiet -framerate 30 -f x11grab -i :0.0 -f alsa -i default -preset veryfast "$VIDEODIR/$FILENAME.mkv" &
    notify-send "Recording" "Video recording started."
    echo "$RECTEMPINFO" > "$RECTEMPFILE"
    update_status
fi
