#! /bin/sh

OUTDIR="/home/$USER/pix/screenshots"
OUTFILE="screenshot_$(date '+%Y-%m-%d_%H-%M-%S').png"

notify() {
    notify-send --icon=camera-photo "Screenshot" "$1 screenshot saved to $OUTFILE"
}

case ${1} in
	"selection")
		maim -u -s "$OUTDIR/$OUTFILE"
		if [ $? -eq 0 ]; then notify "$1"; fi
		;;
	"fullscreen")
		maim -q -d 0.5 "$OUTDIR/$OUTFILE"
		;;
        "window")
		maim -q -d 0.5 -i "$(xdotool getactivewindow)" "$OUTDIR/$OUTFILE"
		;;

esac
