#! /bin/sh

OUTDIR="/home/$USER/pix/screenshots"
OUTFILE="screenshot_$(date '+%Y-%m-%d_%H-%M-%S').png"

notify() {
    notify-send --icon=camera-photo "Screenshot" "$1 screenshot saved to $OUTFILE"
}

# Create output dir if not exist
[ -d "$OUTDIR" ] || mkdir -p "$OUTDIR"

# Choose type of screenshot
case $1 in
    "selection")
        maim -u -s "$OUTDIR/$OUTFILE" && notify "$1";;
    "fullscreen")
        maim -q -d 0.5 "$OUTDIR/$OUTFILE" && notify "$1";;
    "window")
        maim -q -d 0.5 -i "$(xdotool getactivewindow)" "$OUTDIR/$OUTFILE" && notify "$1";;
esac
