#! /bin/sh

OUTDIR="/home/$USER/pix/screenshots"
OUTFILE="screenshot_$(date '+%Y-%m-%d_%H-%M-%S').png"

notify() {
    if echo "$1" | grep -q "clip"; then
        notify-send --icon=camera-photo "Screenshot" "$1 copied to clipboard"
    else
        notify-send --icon=camera-photo "Screenshot" "$1 screenshot saved to $OUTFILE"
    fi
}

# Create output dir if not exist
[ -d "$OUTDIR" ] || mkdir -p "$OUTDIR"

prompt="Select Screenshot Type "
screenshot_type=$(printf "Selection\nClipboard\nFullscreen\nWindow" | dmenu -i -l 4 -p "$prompt")

# Choose type of screenshot
case "$screenshot_type" in
    "Selection")
        maim -u -s "$OUTDIR/$OUTFILE" && notify "$1";;
    "Clipboard")
        maim -u -s | xclip -selection clipboard -t image/png
        if [ -n "$(xclip -selection clipboard -o 2>/dev/null)" ]; then
            notify "$1"
        fi
        ;;
    "Fullscreen")
        maim -q -d 0.5 "$OUTDIR/$OUTFILE" && notify "$1";;
    "Window")
        maim -q -d 0.5 -i "$(xdotool getactivewindow)" "$OUTDIR/$OUTFILE" && notify "$1";;
    *)
        exit 0;;
esac
