#!/usr/bin/env bash
# set -euf -o pipefail
#
# VIM=${VIM:-"vim"}
# TMUX=${TMUX:-"tmux"}
#
# FILE=${FILE:-"$(date +%F).tidal"}
# SESSION=${SESSION:-"tidal"}
#
# TIDAL_BOOT_PATH=${TIDAL_BOOT_PATH:-""}
# GHCI=${GHCI:-""}
#
# args=${@:-$FILE}
#
# # Check if tmux session "tidal" is running, attach only
# # else, create new session, split windows and run processes
# $TMUX -2 attach-session -t $SESSION || $TMUX -2 \
#   new-session -s $SESSION   \; \
#   split-window -v -t $SESSION   \; \
#   send-keys -t 1 "$VIM $args" C-m   \; \
#   send-keys -t 2 "TIDAL_BOOT_PATH=$TIDAL_BOOT_PATH GHCI=$GHCI tidal" C-m   \; \
#   select-pane -t 1
#

# set -euf -o pipefail
#
# VIM=${VIM:-"vim"}
# TMUX=${TMUX:-"tmux"}
#
# FILE=${FILE:-"$(date +%F).tidal"}
# SESSION=${SESSION:-"tidal"}
#
# TIDAL_BOOT_PATH=${TIDAL_BOOT_PATH:-""}
# GHCI=${GHCI:-""}
#
# # Path to sclang executable (customizable via environment variable)
# SCLANG=${SCLANG:-"sclang"}
#
# args=${@:-$FILE}
#
# # Check if tmux session "tidal" is running, attach only
# # else, create new session, set up windows and panes, and run processes
# $TMUX -2 attach-session -t $SESSION || $TMUX -2 \
#   new-session -s $SESSION   \; \
#   split-window -v -t $SESSION:1   \; \
#   send-keys -t $SESSION:1.1 "$VIM $args" C-m   \; \
#   send-keys -t $SESSION:1.2 "TIDAL_BOOT_PATH=$TIDAL_BOOT_PATH GHCI=$GHCI tidal" C-m   \; \
#   new-window -t $SESSION:2   \; \
#   send-keys -t $SESSION:2 "$SCLANG" C-m   \; \
#   select-window -t $SESSION:1   \; \
#   select-pane -t $SESSION:1.1
#

# Check if in tmux
if [ -n "$TMUX" ]; then
  echo "Run outside of tmux session"
  exit 0
fi


cd ~/mus/Tidal

set -euf -o pipefail

VIM=${VIM:-"nvim"}
TMUX=${TMUX:-"tmux"}

FILE=${FILE:-"$(date +%F).tidal"}
SESSION=${SESSION:-"tidal"}

TIDAL_BOOT_PATH=${TIDAL_BOOT_PATH:-""}
GHCI=${GHCI:-""}

# Path to sclang executable (customizable via environment variable)
SCLANG=${SCLANG:-"sclang"}

args=${@:-$FILE}

# Check if tmux session "tidal" is running, attach only
# else, create new session, set up panes in window 1, and run processes
$TMUX -2 attach-session -t $SESSION || $TMUX -2 \
  new-session -s $SESSION   \; \
  split-window -h -t $SESSION:1   \; \
  split-window -v -t $SESSION:1.2   \; \
  send-keys -t $SESSION:1.1 "$VIM $args" C-m   \; \
  send-keys -t $SESSION:1.2 "TIDAL_BOOT_PATH=$TIDAL_BOOT_PATH GHCI=$GHCI tidal" C-m   \; \
  send-keys -t $SESSION:1.3 "$SCLANG" C-m   \; \
  select-pane -t $SESSION:1.1
