#!/bin/sh

# Script for launching or creating VMs with qemu/kvm

vman="Virt Manager"

# Start default network if not active
start_network() {
    net=$(virsh net-list --all | awk 'NR > 2 {print $2}')
    if [[ "$net" == "inactive" ]]; then virsh net-start default; fi
}

# Find available VMs
find_wm() {
    vm_names=$(virsh list --all | awk 'NR > 2 {print $2}')
    dmenu_options=$(echo -e "$vm_names\n$vman")
    if [[ "$vm_names" == "" ]]
    then
        dmenu_options=$(echo -e "$vman")
    fi
    echo "$dmenu_options"
}

# Start selected vm
start_vm() {
    start_network
    #virsh start $1 && virt-viewer $1
    virsh start $1
    virt-manager --no-fork --connect qemu:///system --show-domain-console "$1"
}
# Select a VM from dmenu
vm=$(find_wm)
selected_vm=$(echo "$vm" | dmenu -i -l 5 -p "$vman:")

# Start the selected VM or open virt-manager
if [ "$selected_vm" = "$vman" ]; then
    virt-manager
elif [ -n "$selected_vm" ]; then
    start_vm $selected_vm
else
    echo "No VM selected."
fi

