#! /bin/sh

# Script for adjusting volume, setting statusbar and showing notifiction

MAXVOL=99
MINVOL=0
VOLSTEP=1

update_qtile_bar() {
    qtile cmd-obj -o widget barvolume -f force_update
}

get_vol(){
    def=$(pactl get-default-sink)
    vol=$(pactl get-sink-volume "$def" | sed -n 's/.* \([0-9]\+\)% .*/\1/p; s/.* \([0-9]\+\)%$/\1/p')
    echo $vol
}

get_mute() {
    mute=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{ print $2 }')
    echo $mute
}

notify() {
    if [ "$1" = "mute" ]; then
	if [ $(get_mute) = "yes" ];then
            notify-send --icon=audio-volume-muted -h int:value:"$(get_vol)%" "Volume" "Muted"
	else
            notify-send --icon=audio-volume-medium -h int:value:"$(get_vol)%" "Volume" "$(get_vol)%"
	fi
    else
        notify-send --icon=audio-volume-medium -h int:value:"$(get_vol)%" "Volume" "$(get_vol)%"
    fi
}

toggle_mute() {
    pactl set-sink-mute @DEFAULT_SINK@ toggle
}

set_vol() {
    if [ $(get_mute) = "yes" ]; then
        toggle_mute
    fi
    pactl set-sink-volume @DEFAULT_SINK@ "$1"%
}

update_status() {
    if pgrep -x dwm > /dev/null; then
        pkill -RTMIN+5 slstatus
    elif pgrep -x qtile > /dev/null; then
        update_qtile_bar
    fi
}

volume_pa() {
	def=$(pactl get-default-sink)
	muted=$(pactl get-sink-mute "$def" | awk '/Mute:/ { print $2 }')
	vol=$(pactl get-sink-volume "$def" | sed -n 's/.* \([0-9]\+\)% .*/\1/p; s/.* \([0-9]\+\)%$/\1/p')

	if [ "$muted" = "yes" ]; then
		echo "  mute"
	else
		if [ "$vol" -ge 65 ]; then
			echo "  $vol%"
		elif [ "$vol" -ge 40 ]; then
			echo "  $vol%"
		elif [ "$vol" -ge 0 ]; then
			echo "  $vol%"	
		fi
	fi

}

if [ -n "$1" ]; then
    if [ "$1" = "up" ] && [ $(get_vol) -le $MAXVOL ]; then
        set_vol "+$VOLSTEP"
        notify
        update_status
    elif [ "$1" = "down" ] && [ $(get_vol) -ge $MINVOL ]; then
        set_vol "-$VOLSTEP"
        notify
        update_status
    elif [ "$1" = "mute" ]; then
        toggle_mute
        notify "mute"
        update_status
    elif [ "$1" = "init" ]; then
        sleep 5
        update_status
    elif [ "$1" = "setvolume" ]; then
        v=$(echo "" | dmenu -l 0 -p "Set Volume:")
        if [ $? -eq 0 ] && [ $v -gt -1 ] && [ $v -lt 101 ]
        then
            set_vol "$v"
            notify
            update_status
        fi
    fi
else
    volume_pa
fi

