#! /bin/sh

if ! command -v magick &>/dev/null; then
    notify-send --urgency=critical "Error" "Imagemagick is not installed. Please install it to use this script"
    exit 1
fi

wallpaperDir="$HOME/pix/wallpapers"
wp="$HOME/.local/share/background/wp.png"
wptmp="$HOME/.local/share/background/wptmp.png"
loginmanager="/usr/share/sddm/themes/monochrome-rs/backgrounds/wp.png"

set_wallpaper() {
    xwallpaper --zoom "$wp" &
}

set_login_background() {
    magick "$wp" -fill "rgba(0, 0, 0, 0.3)" -colorize 70% "$wptmp"
    # TODO: check if other options to do this
    # to make the copy command work, the following was done, sudo visudo -> add to sudoers file:
    # user ALL=(ALL) NOPASSWD: /usr/bin/cp /home/user/.local/share/background/wptmp.png /usr/share/sddm/themes/monochrome-rs/backgrounds/wp.png
    cp "$wptmp" "$loginmanager"
    rm "$wptmp"
}

# check if wallpaper dir exists
if [ ! -d "$wallpaperDir" ]; then
    mkdir -p "$wallpaperDir"
fi

# check if background dir exists
if [ ! -d "$(dirname "$wp")" ]; then
    mkdir -p "$(dirname "$wp")"
fi

# Set option based on flags or use dmenu
if [ "$1" = "--reload" ]; then
    option="Reload"
elif [ "$1" = "--random" ]; then
    option="Random"
else
    option=$(printf "Random\nReload\n$(ls "$wallpaperDir")" | dmenu -i -l 15 -p "Wallpaper")
fi

case $option in
    "")
        exit
        ;;
    "Random")
        newWp=$(ls "$wallpaperDir" | shuf -n 1)
        ;;
    "Reload")
        set_wallpaper
        exit
        ;;
    *)
        newWp=$option
        ;;
esac

if [ "$newWp" = "" ]; then
    notify-send --urgency=critical "Wallpaper" "Wallpaper directory empty"
else
    # Get the MIME type of the selected file
    mimeType=$(file --mime-type -b "$wallpaperDir/$newWp")

    if [ "$mimeType" = "image/png" ]; then
        # File is already a PNG; just copy it
        cp "$wallpaperDir/$newWp" "$wp"
    else
        # Convert to PNG
        ffmpeg -loglevel quiet -y -i "$wallpaperDir/$newWp" "$wp"
    fi

    set_wallpaper
    set_login_background
fi
