#!/bin/sh

# if [ "$XDG_SESSION_TYPE" = "wayland" ]; then


if ! command -v magick &>/dev/null; then
    notify-send --urgency=critical "Error" "Imagemagick is not installed. Please install it to use this script"
    exit 1
fi

wallpaperDir="$HOME/pix/wallpapers"
wp="$HOME/pix/wallpapers/.current"
# wp="$HOME/.local/share/background/wp.png"
loginmanager="/usr/share/sddm/themes/monochrome-rs/backgrounds/wp.png"
currentFile="$wallpaperDir/.name_of_current"

desaturate_and_colorize() {
    magick "$wp" -modulate 100,0 "$wp"
    magick "$wp" -fill "rgba(0, 0, 0, 1.0)" -colorize 60% "$wp"
}

set_wallpaper() {
    # xwallpaper --zoom "$wp" &
    swaybg -i "$wp" -m fill
    # hyprctl hyprpaper reload , "$wp"
}

set_login_background() {
    # TODO: check if other options to do this
    # to make the copy command work, the following was done, sudo visudo -> add to sudoers file:
    # user ALL=(ALL) NOPASSWD: /usr/bin/cp /home/user/.local/share/background/wp.png /usr/share/sddm/themes/monochrome-rs/backgrounds/wp.png
    cp "$wp" "$loginmanager"
}

# Check if wallpaper dir exists
if [ ! -d "$wallpaperDir" ]; then
    mkdir -p "$wallpaperDir"
fi

# Check if background dir exists
if [ ! -d "$(dirname "$wp")" ]; then
    mkdir -p "$(dirname "$wp")"
fi

# Get the current wallpaper name from .current file (if it exists)
currentWp=""
if [ -f "$currentFile" ]; then
    currentWp=$(cat "$currentFile")
fi

# Set option based on flags or use dmenu
if [ "$1" = "--reload" ]; then
    option="Reload"
elif [ "$1" = "--random" ]; then
    option="Random"
elif [ "$1" = "--nsxiv" ]; then
    option="nsxiv"

else
  if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    # List wallpapers excluding .current and current wallpaper
    wallpaperList=$(ls "$wallpaperDir" | grep -v -e "^\.current$" -e "^${currentWp}$" -e "^README\.md$")
    option=$(printf "Preview\nRandom\nReload\n${wallpaperList}" | wmenu -f "Hack Bold 16" -c -i -l 15 $WMENU_COLORS -p "Wallpaper")
    # option=$(printf "Preview\nRandom\nReload\n${wallpaperList}" | rofi -dmenu -i -l 15 -p "Wallpaper")
  else
    # List wallpapers excluding .current and current wallpaper
    wallpaperList=$(ls "$wallpaperDir" | grep -v -e "^\.current$" -e "^${currentWp}$" -e "^README\.md$")
    option=$(printf "Preview\nRandom\nReload\n${wallpaperList}" | dmenu -i -l 15 -p "Wallpaper")
  fi
fi

case $option in
    "")
        exit
        ;;
    "Random")
        # Select a random wallpaper excluding the current one and .current
        newWp=$(ls "$wallpaperDir" | grep -v -e "^\.current$" -e "^${currentWp}$" | shuf -n 1)
        ;;
    "Reload")
        set_wallpaper
        exit
        ;;
    "Preview")
        # Select a wallpaper using nsxiv for preview, wpicker name used to set floating window in dwm
        imgpath=$(nsxiv -r -N wpicker /home/rs/pix/wallpapers -t --alpha-layer -o -b)
        if [ -z "$imgpath" ]; then
            exit
        fi

        newWp=$(basename "$imgpath")
        ;;
    *)
        newWp=$option
        ;;
esac


if [ "$newWp" = "" ]; then
    notify-send --urgency=critical "Wallpaper" "Wallpaper directory empty or no valid wallpapers available"
else
    # Get the MIME type of the selected file
    mimeType=$(file --mime-type -b "$wallpaperDir/$newWp")

    if [ "$mimeType" = "image/png" ]; then
        # File is already a PNG; just copy it
        echo "cp $wallpaperDir/$newWp $wp"
        cp "$wallpaperDir/$newWp" "$wp"
    else
        # Convert to PNG
        echo "cp $wallpaperDir/$newWp $wp"
        echo "ffmpeg -loglevel quiet -y -i $wallpaperDir/$newWp $wp"
        ffmpeg -loglevel quiet -y -i "$wallpaperDir/$newWp" "$wp"
    fi

    # Save the new wallpaper name to .current
    echo "$newWp" > "$currentFile"

    # Desaturate and colorize image
    # desaturate_and_colorize


    set_wallpaper
    # set_login_background
fi

exit 0
