#!/bin/sh

if ! command -v magick &>/dev/null; then
    notify-send --urgency=critical "Error" "Imagemagick is not installed. Please install it to use this script"
    exit 1
fi

wallpaperDir="$HOME/pix/wallpapers"
wp="$HOME/.local/share/background/wp.png"
wptmp="$HOME/.local/share/background/wptmp.png"
loginmanager="/usr/share/sddm/themes/monochrome-rs/backgrounds/wp.png"
currentFile="$wallpaperDir/.current"

set_wallpaper() {
    xwallpaper --zoom "$wp" &
}

set_login_background() {
    magick "$wp" -fill "rgba(0, 0, 0, 0.3)" -colorize 70% "$wptmp"
    # TODO: check if other options to do this
    # to make the copy command work, the following was done, sudo visudo -> add to sudoers file:
    # user ALL=(ALL) NOPASSWD: /usr/bin/cp /home/user/.local/share/background/wptmp.png /usr/share/sddm/themes/monochrome-rs/backgrounds/wp.png
    cp "$wptmp" "$loginmanager"
    rm "$wptmp"
}

# Check if wallpaper dir exists
if [ ! -d "$wallpaperDir" ]; then
    mkdir -p "$wallpaperDir"
fi

# Check if background dir exists
if [ ! -d "$(dirname "$wp")" ]; then
    mkdir -p "$(dirname "$wp")"
fi

# Get the current wallpaper name from .current file (if it exists)
currentWp=""
if [ -f "$currentFile" ]; then
    currentWp=$(cat "$currentFile")
fi

# Set option based on flags or use dmenu
if [ "$1" = "--reload" ]; then
    option="Reload"
elif [ "$1" = "--random" ]; then
    option="Random"
elif [ "$1" = "--nsxiv" ]; then
    option="nsxiv"

else
    # List wallpapers excluding .current and current wallpaper
    wallpaperList=$(ls "$wallpaperDir" | grep -v -e "^\.current$" -e "^${currentWp}$" -e "^README\.md$")
    option=$(printf "Preview\nRandom\nReload\n${wallpaperList}" | dmenu -i -l 15 -p "Wallpaper")
fi

case $option in
    "")
        exit
        ;;
    "Random")
        # Select a random wallpaper excluding the current one and .current
        newWp=$(ls "$wallpaperDir" | grep -v -e "^\.current$" -e "^${currentWp}$" | shuf -n 1)
        ;;
    "Reload")
        newWp=$(cat $currentFile)
        ;;
    "Preview")
        # Select a wallpaper using nsxiv for preview
        imgpath=$(nsxiv -r /home/rs/pix/wallpapers -t --alpha-layer -o -b)
        if [ -z "$imgpath" ]; then
            exit
        fi
        newWp=$(basename "$imgpath")
        ;;
    *)
        newWp=$option
        ;;
esac

if [ "$newWp" = "" ]; then
    notify-send --urgency=critical "Wallpaper" "Wallpaper directory empty or no valid wallpapers available"
else
    # Get the MIME type of the selected file
    mimeType=$(file --mime-type -b "$wallpaperDir/$newWp")

    if [ "$mimeType" = "image/png" ]; then
        # File is already a PNG; just copy it
        cp "$wallpaperDir/$newWp" "$wp"
    else
        # Convert to PNG
        ffmpeg -loglevel quiet -y -i "$wallpaperDir/$newWp" "$wp"
    fi

    # Save the new wallpaper name to .current
    echo "$newWp" > "$currentFile"

    set_wallpaper
    set_login_background
fi

