#!/bin/sh

# Websearch with dmenu

search_engine=$(printf "Google\nDuckDuckGo\nYouTube\nBing\nSearx\nOdysee" | sort | dmenu -i -l 20 -p "Choose Search:")

case "$search_engine" in 
    "Google")
        echo $(echo "" | dmenu -p "Google Search:" | xargs -I{} xdg-open https://www.google.com/search?q={})
	;;
    "DuckDuckGo")
        echo $(echo "" | dmenu -p "DuckDuckGo Search:" | xargs -I{} xdg-open https://www.duckduckgo.com/?q={})
	;;
    "YouTube")
        echo $(echo "" | dmenu -p "YouTube Search:" | xargs -I{} xdg-open https://www.youtube.com/results?search_query={})
	;;
    "Bing")
        echo $(echo "" | dmenu -p "Bing Search:" | xargs -I{} xdg-open https://www.bing.com/search?q={})
	;;
    "Searx")
        echo $(echo "" | dmenu -p "Searx Search:" | xargs -I{} xdg-open https://searx.tiekoetter.com/search?q={})
	;;
    "Odysee")
        echo $(echo "" | dmenu -p "Odysee Search:" | xargs -I{} xdg-open https://odysee.com/$/search?q={})
esac

